import type { CAMCategoria } from "../types";

/** Categorie CAM standard (riferimento ANAC / DM 23/06/2022). */
export const CAM_CATEGORIE_STANDARD: CAMCategoria[] = [
  {
    id: "cam-mat-001",
    codice: "CAM-01",
    nome: "Cemento a basse emissioni",
    descrizione: "Utilizzo di cemento con ridotta impronta carbonica (CSC, CSA, ecc.)",
    tipologia: "MATERIALE",
    obbligatorio: true,
    percentualeMinimaApplicazione: 100,
    scorePunti: 15,
    documentazionerichiesta: [
      "Dichiarazione di conformità fornitore",
      "EPD (Environmental Product Declaration)",
    ],
    note: "Obbligatorio per opere in cemento armato > 100 m³",
  },
  {
    id: "cam-mat-002",
    codice: "CAM-02",
    nome: "Acciaio riciclato",
    descrizione: "Acciaio da riciclaggio vs acciaio primario",
    tipologia: "MATERIALE",
    obbligatorio: true,
    percentualeMinimaApplicazione: 70,
    scorePunti: 12,
    documentazionerichiesta: ["Certificazione riciclabilità", "Scheda tecnica materiale"],
    note: "Minimo 70% acciaio da rifiuti",
  },
  {
    id: "cam-ene-001",
    codice: "CAM-03",
    nome: "Efficienza energetica cantiere",
    descrizione: "Illuminazione LED, gestione energia da rinnovabili",
    tipologia: "ENERGIA",
    obbligatorio: true,
    percentualeMinimaApplicazione: 80,
    scorePunti: 20,
    documentazionerichiesta: [
      "Piano energetico cantiere",
      "Certificazioni impianti LED/rinnovabili",
    ],
    note: "Minimo 80% consumi da LED o rinnovabili",
  },
  {
    id: "cam-rif-001",
    codice: "CAM-04",
    nome: "Gestione rifiuti da demolizione",
    descrizione: "Raccolta differenziata, riciclaggio materiali da demolizione",
    tipologia: "RIFIUTI",
    obbligatorio: true,
    percentualeMinimaApplicazione: 90,
    scorePunti: 15,
    documentazionerichiesta: ["Piano gestione rifiuti", "Accordi con centri riciclaggio"],
    note: "Minimo 90% dei rifiuti riciclato/riutilizzato",
  },
  {
    id: "cam-tra-001",
    codice: "CAM-05",
    nome: "Trasporto sostenibile materiali",
    descrizione: "Utilizzo di mezzi Euro 6, valutazione logistica",
    tipologia: "TRASPORTO",
    obbligatorio: false,
    percentualeMinimaApplicazione: 50,
    scorePunti: 10,
    documentazionerichiesta: ["Certificazioni mezzi Euro 6", "Piano logistica"],
    note: "Bonus punti se attivato",
  },
];
